# Generated by Django 3.2.13 on 2023-01-28 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equiptypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiptype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date'),
        ),
        migrations.AddField(
            model_name='equiptype',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Name'),
        ),
    ]
