# Generated by Django 4.1.5 on 2023-01-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equiptypes', '0002_auto_20230128_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiptype',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
    ]
