# Generated by Django 3.2.13 on 2023-01-27 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name/model')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('factory_num', models.CharField(blank=True, max_length=20, verbose_name='Factory number')),
                ('inventory_num', models.CharField(blank=True, max_length=20, verbose_name='Inventory number')),
                ('registr_num', models.CharField(blank=True, max_length=20, verbose_name='Registration number')),
                ('start_op_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start operation date')),
                ('op_time', models.IntegerField(blank=True, verbose_name='Total operation time')),
                ('last_repair_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last repair date')),
                ('op_time_after_repairs', models.IntegerField(blank=True, verbose_name='Operation time after major repairs')),
            ],
        ),
    ]
