# Generated by Django 3.2.13 on 2023-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='last_repair_date',
            field=models.DateTimeField(blank=True, verbose_name='Last repair date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='start_op_date',
            field=models.DateTimeField(blank=True, verbose_name='Start operation date'),
        ),
    ]
