# Generated by Django 3.2.13 on 2023-01-25 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20230125_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='last_repair_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last repair date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='start_op_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start operation date'),
        ),
    ]
