# Generated by Django 3.2.13 on 2023-01-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20230127_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='registr_num',
            new_name='register_num',
        ),
    ]
