# Generated by Django 3.2.13 on 2023-01-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equiptypes', '0001_initial'),
        ('stations', '0003_alter_station_address'),
        ('equipment', '0003_rename_registr_num_equipment_register_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='equiptypes', to='equiptypes.equiptype', verbose_name='Equipment type'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='stations.station', verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='factory_num',
            field=models.CharField(blank=True, max_length=12, verbose_name='Factory number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_num',
            field=models.CharField(blank=True, max_length=12, verbose_name='Inventory number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='register_num',
            field=models.CharField(blank=True, max_length=16, verbose_name='Registration number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='station_num',
            field=models.CharField(blank=True, max_length=4, verbose_name='Station number'),
        ),
    ]
