# Generated by Django 4.1.5 on 2023-02-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equiptypes', '0003_alter_equiptype_name'),
        ('equipment', '0008_alter_equipment_name_alter_equipment_register_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equiptypes', to='equiptypes.equiptype', verbose_name='Equipment type'),
        ),
    ]
