# Generated by Django 4.1.5 on 2023-02-05 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='method',
            field=models.CharField(choices=[('Visual testing method', 'Visual testing method'), ('Ultrasonic testing method', 'Ultrasonic testing method'), ('Penetrant testing method', 'Penetrant testing method'), ('Magneting particle testing method', 'Magneting particle testing method')], default='Visual testing method', max_length=16, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 4, 21, 2, 47, 570625, tzinfo=datetime.timezone.utc), verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.CharField(choices=[('2nd level', '2nd level'), ('3rd level', '3rd level')], default='2nd level', max_length=16, verbose_name='Level'),
        ),
    ]
