# Generated by Django 4.1.5 on 2023-02-05 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_method_alter_certificate_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 4, 21, 22, 57, 145358, tzinfo=datetime.timezone.utc), verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='method',
            field=models.CharField(choices=[('Visual testing method', 'Visual testing method'), ('Ultrasonic testing method', 'Ultrasonic testing method'), ('Penetrant testing method', 'Penetrant testing method'), ('Magneting particle testing method', 'Magneting particle testing method')], default='Visual testing method', max_length=32, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.CharField(max_length=32),
        ),
    ]
