# Generated by Django 4.1.5 on 2023-02-21 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0002_certificate_method_alter_certificate_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.CharField(default='BY/112 09.01 080.01 00777', max_length=32, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
