# Generated by Django 4.1.5 on 2023-02-05 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 4, 21, 24, 46, 788643, tzinfo=datetime.timezone.utc), verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.CharField(choices=[('2nd level', '2nd level'), ('3rd level', '3rd level')], default='2nd level', max_length=12, verbose_name='Level'),
        ),
    ]
