# Generated by Django 4.1.5 on 2023-02-05 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificate_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2028, 2, 4, 21, 25, 7, 995461, tzinfo=datetime.timezone.utc), verbose_name='Finish date'),
        ),
    ]
