# Generated by Django 4.1.5 on 2023-02-05 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificate_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Finish date'),
        ),
    ]
