# Generated by Django 4.1.5 on 2023-02-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_alter_certificate_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.CharField(choices=[('2nd level', '2nd level'), ('3rd level', '3rd level')], default='2nd level', max_length=9, verbose_name='Level'),
        ),
    ]
