# Generated by Django 4.1.5 on 2023-02-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_alter_certificate_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.CharField(choices=[('2nd level', '2nd level'), ('3rd level', '3rd level')], default='2nd level', max_length=16, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='method',
            field=models.CharField(choices=[('Visual testing method', 'Visual testing method'), ('Ultrasonic testing method', 'Ultrasonic testing method'), ('Penetrant testing method', 'Penetrant testing method'), ('Magneting particle testing method', 'Magneting particle testing method')], default='Visual testing method', max_length=48, verbose_name='Method'),
        ),
    ]
