# Generated by Django 4.1.5 on 2023-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_alter_certificate_level_alter_certificate_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.CharField(default='BY/112 09.01 080.01 00777', max_length=32),
        ),
    ]
