# Generated by Django 3.2.13 on 2023-01-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(default='', max_length=120, verbose_name='Address'),
        ),
    ]
