# Generated by Django 3.2.13 on 2023-01-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Address'),
        ),
    ]
