# Generated by Django 4.1.5 on 2023-01-31 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0008_alter_equipment_name_alter_equipment_register_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Report name')),
                ('report_type', models.CharField(choices=[('NDT', 'NDT Report'), ('TD', 'TD Report')], default='NDT', max_length=12, verbose_name='Report type')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('report_date', models.DateField(default=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date'), verbose_name='Report date')),
                ('report_num', models.CharField(max_length=10, unique=True, verbose_name='Report number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.equipment', verbose_name='Equipment')),
            ],
        ),
    ]
