# Generated by Django 4.1.5 on 2023-02-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_station_name'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, upload_to='reports/uploads/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.station', verbose_name='Station'),
        ),
    ]
