# Generated by Django 4.1.5 on 2023-01-31 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.AddField(
            model_name='report',
            name='parts_names',
            field=models.CharField(blank=True, max_length=120, verbose_name='Parts names'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Report date'),
        ),
    ]
