# Generated by Django 4.1.5 on 2023-02-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='station',
        ),
    ]
