# Generated by Django 4.1.5 on 2023-02-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_name_report_parts_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_num',
            field=models.CharField(default='01-2023', max_length=10, unique=True, verbose_name='Report number'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('NDT', 'NDT'), ('TD', 'TD')], default='NDT', max_length=12, verbose_name='Report type'),
        ),
    ]
