# Generated by Django 4.1.5 on 2023-02-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, upload_to='reports/uploads/%Y-%m-%d/'),
        ),
    ]
